CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  tg_id BIGINT UNIQUE NOT NULL,
  username TEXT
);
CREATE TABLE IF NOT EXISTS slots (
  id SERIAL PRIMARY KEY,
  start_utc TIMESTAMPTZ NOT NULL,
  end_utc   TIMESTAMPTZ NOT NULL,
  is_booked BOOLEAN NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS bookings (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slot_id INTEGER NOT NULL REFERENCES slots(id) ON DELETE CASCADE,
  status  TEXT NOT NULL DEFAULT 'requested',
  paid    BOOLEAN NOT NULL DEFAULT false
);
